/* dashboard.js — tabbed workspace (Overview, Market Scanner, AI Signals,
   Portfolio, Risk Manager, Reports), AI control center, live WS updates. */

let currentSettings = { max_trades: 5 };
let currentView = "overview";

const VIEW_META = {
  overview:  { heading: "Welcome",        sub: "Live account snapshot & AI market intelligence" },
  scanner:   { heading: "Market Scanner", sub: "Live confidence scan across the broader instrument universe" },
  signals:   { heading: "AI Signals",     sub: "Signal history generated by the analysis engine" },
  portfolio: { heading: "Portfolio",      sub: "Account balance, open positions, and trade history" },
  risk:      { heading: "Risk Manager",   sub: "Exposure, drawdown, and position sizing controls" },
  reports:   { heading: "Reports",        sub: "Performance breakdown across all closed trades" },
  analyst:   { heading: "AI Analyst",     sub: "Educational technical analysis for any pair — not financial advice" },
  calculator:{ heading: "Risk Calculator",sub: "Suggested position size from your balance, risk %, and stop-loss" },
  journal:   { heading: "Trading Journal",sub: "Strategy, notes, and emotion tracking on every trade" },
  calendar:  { heading: "Economic Calendar", sub: "Upcoming macro events that tend to move forex markets" },
  backtest:  { heading: "Strategy Backtester", sub: "Test an EMA crossover strategy against historical data" },
};

document.addEventListener("DOMContentLoaded", async () => {
  const user = await initShell("dashboard");
  if (!user) return;

  wireNav();
  wireButtons();
  connectWebSocket(handleWsMessage);
  await loadSettingsForCaps();

  const initialView = (location.hash || "#overview").replace("#", "");
  switchView(VIEW_META[initialView] ? initialView : "overview");
});

function wireNav() {
  document.querySelectorAll(".nav-link[data-view]").forEach((el) => {
    el.addEventListener("click", (e) => {
      e.preventDefault();
      history.replaceState(null, "", `#${el.dataset.view}`);
      switchView(el.dataset.view);
    });
  });
}

function switchView(view) {
  currentView = view;
  document.querySelectorAll(".view").forEach((el) => (el.hidden = true));
  document.getElementById(`view-${view}`).hidden = false;
  document.querySelectorAll(".nav-link").forEach((el) => el.classList.toggle("active", el.dataset.view === view));

  const meta = VIEW_META[view];
  document.getElementById("view-heading").textContent =
    view === "overview" && window.__username ? `Welcome, ${window.__username}` : meta.heading;
  document.getElementById("view-subheading").textContent = meta.sub;

  loadViewData(view);
}

async function loadViewData(view) {
  switch (view) {
    case "overview":  await Promise.all([loadAccount(), loadPositions(), loadRiskStatus(), loadSignals(), loadBotStatus()]); break;
    case "scanner":   await loadScanner(); break;
    case "signals":   await loadSignalHistory(); break;
    case "portfolio": await loadPortfolio(); break;
    case "risk":      await loadRiskDetail(); break;
    case "reports":   await loadReports(); break;
    case "analyst":   /* runs on demand via button, nothing to preload */ break;
    case "calculator":/* runs on demand via form submit */ break;
    case "journal":   await loadJournal(); break;
    case "calendar":  await loadCalendar(); break;
    case "backtest":  /* runs on demand via form submit */ break;
  }
}

async function loadSettingsForCaps() {
  try {
    currentSettings = await api.getSettings();
    const el = document.getElementById("stat-max-trades");
    if (el) el.textContent = currentSettings.max_trades;
  } catch (_) {}
}

async function loadAccount() {
  try {
    const acct = await api.account();
    document.getElementById("stat-balance").textContent = fmtMoney(acct.balance);
    document.getElementById("stat-equity").textContent = fmtMoney(acct.equity);
    document.getElementById("stat-currency").textContent = acct.currency;
    document.getElementById("stat-margin-level").textContent = fmtPct(acct.margin_level);

    const dot = document.getElementById("mt5-dot");
    const text = document.getElementById("mt5-text");
    dot.classList.add("on"); dot.classList.remove("off");
    text.textContent = acct.mock ? "MT5 · Mock data" : `MT5 · ${acct.server}`;
  } catch (err) { showToast(err.message, "error"); }
}

async function loadPositions() {
  const body = document.getElementById("positions-body");
  try {
    const positions = await api.positions();
    document.getElementById("stat-open-trades").textContent = positions.length;

    const dailyProfit = positions.reduce((sum, p) => sum + p.profit, 0);
    const sub = document.getElementById("stat-daily-profit");
    sub.textContent = fmtMoney(dailyProfit);
    sub.className = `stat-value ${dailyProfit >= 0 ? "up" : "down"}`;
    document.getElementById("stat-daily-profit-sub").textContent = `${positions.length} open position(s)`;

    body.innerHTML = renderPositionsRows(positions, true);
    wireCloseButtons(body);
  } catch (_) {
    body.innerHTML = `<tr><td colspan="7" class="empty-state">Failed to load positions.</td></tr>`;
  }
}

function renderPositionsRows(positions, withClose) {
  if (!positions.length) return `<tr><td colspan="7" class="empty-state">No open positions.</td></tr>`;
  return positions.map((p) => `
    <tr>
      <td><strong>${p.symbol}</strong></td>
      <td><span class="opp-dir ${p.type}">${p.type}</span></td>
      <td>${p.volume}</td>
      <td>${p.open_price}</td>
      <td>${p.current_price}</td>
      <td class="${p.profit >= 0 ? "up" : "down"}">${fmtMoney(p.profit)}</td>
      <td>${withClose ? `<button class="btn btn-ghost" data-close-ticket="${p.ticket}">Close</button>` : ""}</td>
    </tr>
  `).join("");
}

function wireCloseButtons(container) {
  container.querySelectorAll("[data-close-ticket]").forEach((btn) => {
    btn.addEventListener("click", () => closeTrade(Number(btn.dataset.closeTicket)));
  });
}

async function loadRiskStatus() {
  const card = document.getElementById("risk-card");
  try { card.innerHTML = riskStatusHtml(await api.riskStatus()); }
  catch (_) { card.innerHTML = `<div class="empty-state">Failed to load risk status.</div>`; }
}

function riskStatusHtml(r) {
  return `
    <div class="opp-row"><span class="muted">Daily Risk</span><strong>${fmtPct(r.daily_risk_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Risk Used Today</span><strong>${fmtPct(r.daily_risk_used_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Exposure</span><span class="tag ${r.exposure}">${r.exposure}</span></div>
    <div class="opp-row"><span class="muted">Drawdown</span><strong>${fmtPct(r.drawdown_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Open / Max Trades</span><strong>${r.open_trades} / ${r.max_trades}</strong></div>
    <div class="opp-row"><span class="muted">Max Daily Loss</span><strong>${fmtPct(r.max_daily_loss_percent)}</strong></div>
  `;
}

async function loadSignals() {
  try { renderOpportunities(await api.signals(6)); } catch (_) {}
}

function renderOpportunities(signals) {
  const card = document.getElementById("opportunities-card");
  if (!signals.length) {
    card.innerHTML = `<div class="empty-state">Run <strong>Analyze Markets</strong> to generate AI signals.</div>`;
    return;
  }
  card.innerHTML = signals.map((s) => `
    <div class="opp-row">
      <div class="opp-symbol">${s.symbol} <span class="opp-dir ${s.direction}">${s.direction}</span></div>
      <div style="display:flex;align-items:center;gap:10px;">
        <div class="confidence-bar-track"><div class="confidence-bar-fill" style="width:${s.confidence}%"></div></div>
        <span class="confidence-pct">${s.confidence}%</span>
      </div>
    </div>
  `).join("");
}

async function loadBotStatus() {
  try { setBotStatusLine((await api.botStatus()).running); } catch (_) {}
}

function setBotStatusLine(running) {
  const el = document.getElementById("bot-status-line");
  if (el) el.textContent = `Bot status: ${running ? "🟢 Running (Auto Mode) — checks every ~45s" : "⚪ Stopped"}`;
}

function wireButtons() {
  document.getElementById("btn-analyze").addEventListener("click", runAnalysis);
  document.getElementById("btn-generate").addEventListener("click", runAnalysis);

  const signalsGenBtn = document.getElementById("btn-signals-generate");
  if (signalsGenBtn) signalsGenBtn.addEventListener("click", async () => { await runAnalysis(); await loadSignalHistory(); });

  const rescanBtn = document.getElementById("btn-rescan");
  if (rescanBtn) rescanBtn.addEventListener("click", loadScanner);

  const analystBtn = document.getElementById("btn-analyst-run");
  if (analystBtn) analystBtn.addEventListener("click", runAnalyst);

  const calcForm = document.getElementById("calc-form");
  if (calcForm) calcForm.addEventListener("submit", runRiskCalculator);

  const btForm = document.getElementById("bt-form");
  if (btForm) btForm.addEventListener("submit", runBacktest);

  document.getElementById("btn-start-bot").addEventListener("click", async (e) => {
    e.target.disabled = true;
    try {
      setBotStatusLine((await api.botStart()).running);
      showToast("Auto mode started — bot will trade on high-confidence signals", "success");
    } catch (err) { showToast(err.message, "error"); }
    finally { e.target.disabled = false; }
  });

  document.getElementById("btn-stop-bot").addEventListener("click", async (e) => {
    e.target.disabled = true;
    try {
      setBotStatusLine((await api.botStop()).running);
      showToast("Bot stopped", "success");
    } catch (err) { showToast(err.message, "error"); }
    finally { e.target.disabled = false; }
  });
}

async function runAnalysis() {
  const btn = document.getElementById("btn-analyze");
  const btn2 = document.getElementById("btn-generate");
  if (btn) { btn.disabled = true; btn.textContent = "🔍 Analyzing…"; }
  if (btn2) btn2.disabled = true;
  try {
    const results = await api.analyze();
    renderOpportunities(results);
    if (currentView === "overview") await loadPositions();
    showToast(`Analysis complete — ${results.length} symbols scanned`, "success");
  } catch (err) { showToast(err.message, "error"); }
  finally {
    if (btn) { btn.disabled = false; btn.textContent = "🔍 Analyze Markets"; }
    if (btn2) btn2.disabled = false;
  }
}

async function closeTrade(ticket) {
  try {
    await api.tradeClose(ticket);
    showToast(`Position ${ticket} closed`, "success");
    await loadViewData(currentView);
  } catch (err) { showToast(err.message, "error"); }
}

async function loadScanner() {
  const body = document.getElementById("scanner-body");
  body.innerHTML = `<tr><td colspan="6" class="empty-state">Scanning…</td></tr>`;
  try {
    const rows = await api.scanner();
    if (!rows.length) { body.innerHTML = `<tr><td colspan="6" class="empty-state">No data.</td></tr>`; return; }
    body.innerHTML = rows.map((r) => `
      <tr>
        <td><strong>${r.symbol}</strong></td>
        <td>${r.price ?? "—"}</td>
        <td class="${r.change_pct >= 0 ? "up" : "down"}">${r.change_pct >= 0 ? "+" : ""}${r.change_pct}%</td>
        <td><span class="opp-dir ${r.direction}">${r.direction}</span></td>
        <td>
          <div style="display:flex;align-items:center;gap:10px;">
            <div class="confidence-bar-track" style="width:80px"><div class="confidence-bar-fill" style="width:${r.confidence}%"></div></div>
            <span class="confidence-pct">${r.confidence}%</span>
          </div>
        </td>
        <td><span class="tag ${r.risk}">${r.risk}</span></td>
      </tr>
    `).join("");
  } catch (_) { body.innerHTML = `<tr><td colspan="6" class="empty-state">Failed to scan markets.</td></tr>`; }
}

async function loadSignalHistory() {
  const body = document.getElementById("signals-body");
  try {
    const signals = await api.signals(30);
    if (!signals.length) { body.innerHTML = `<tr><td colspan="6" class="empty-state">No signals yet — click Generate New Signals.</td></tr>`; return; }
    body.innerHTML = signals.map((s) => `
      <tr>
        <td class="muted">${s.created_at}</td>
        <td><strong>${s.symbol}</strong></td>
        <td><span class="opp-dir ${s.direction}">${s.direction}</span></td>
        <td>${s.confidence}%</td>
        <td><span class="tag ${s.risk}">${s.risk}</span></td>
        <td class="muted">${(s.reason || []).join(", ")}</td>
      </tr>
    `).join("");
  } catch (_) { body.innerHTML = `<tr><td colspan="6" class="empty-state">Failed to load signal history.</td></tr>`; }
}

async function loadPortfolio() {
  try {
    const [acct, positions, history] = await Promise.all([api.account(), api.positions(), api.history(30)]);

    document.getElementById("pf-balance").textContent = fmtMoney(acct.balance);
    document.getElementById("pf-equity").textContent = fmtMoney(acct.equity);
    document.getElementById("pf-margin").textContent = fmtMoney(acct.free_margin);
    document.getElementById("pf-leverage").textContent = `1:${acct.leverage}`;

    const posBody = document.getElementById("pf-positions-body");
    posBody.innerHTML = renderPositionsRows(positions, true);
    wireCloseButtons(posBody);

    const histBody = document.getElementById("pf-history-body");
    histBody.innerHTML = !history.length
      ? `<tr><td colspan="5" class="empty-state">No trade history yet.</td></tr>`
      : history.map((h) => `
          <tr>
            <td><strong>${h.symbol}</strong></td>
            <td><span class="opp-dir ${h.type}">${h.type}</span></td>
            <td>${h.volume}</td>
            <td class="${h.profit >= 0 ? "up" : "down"}">${fmtMoney(h.profit)}</td>
            <td class="muted">${h.closed_at}</td>
          </tr>
        `).join("");
  } catch (err) { showToast(err.message, "error"); }
}

async function loadRiskDetail() {
  const card = document.getElementById("risk-detail-card");
  try { card.innerHTML = riskStatusHtml(await api.riskStatus()); }
  catch (_) { card.innerHTML = `<div class="empty-state">Failed to load risk status.</div>`; }
}

async function loadReports() {
  try {
    const [summary, trades] = await Promise.all([api.reportsSummary(), api.reportsTrades(50)]);

    document.getElementById("rp-pnl").textContent = fmtMoney(summary.total_pnl);
    document.getElementById("rp-pnl").className = `stat-value ${summary.total_pnl >= 0 ? "up" : "down"}`;
    document.getElementById("rp-winrate").textContent = fmtPct(summary.win_rate);
    document.getElementById("rp-best").textContent = fmtMoney(summary.best_trade);
    document.getElementById("rp-worst").textContent = fmtMoney(summary.worst_trade);

    const bySymbolCard = document.getElementById("rp-by-symbol");
    bySymbolCard.innerHTML = !summary.by_symbol.length
      ? `<div class="empty-state">No closed trades yet.</div>`
      : summary.by_symbol.map((s) => `
          <div class="opp-row">
            <span><strong>${s.symbol}</strong> <span class="muted">(${s.trades} trades)</span></span>
            <span class="${s.pnl >= 0 ? "up" : "down"}">${fmtMoney(s.pnl)}</span>
          </div>
        `).join("");

    const tradesBody = document.getElementById("rp-trades-body");
    tradesBody.innerHTML = !trades.length
      ? `<tr><td colspan="4" class="empty-state">No trades yet.</td></tr>`
      : trades.map((t) => `
          <tr>
            <td><strong>${t.symbol}</strong></td>
            <td><span class="opp-dir ${t.type}">${t.type}</span></td>
            <td class="${(t.profit || 0) >= 0 ? "up" : "down"}">${t.profit !== null ? fmtMoney(t.profit) : "—"}</td>
            <td><span class="tag ${t.status === "OPEN" ? "MEDIUM" : "LOW"}">${t.status}</span></td>
          </tr>
        `).join("");
  } catch (err) { showToast(err.message, "error"); }
}

function handleWsMessage(msg) {
  switch (msg.event) {
    case "trade_opened":
    case "trade_closed":
      if (currentView === "overview") { loadPositions(); loadRiskStatus(); }
      if (currentView === "portfolio") loadPortfolio();
      break;
    case "bot_trade":
      showToast(`🤖 Bot opened ${msg.data.type} ${msg.data.symbol} (${msg.data.confidence}% confidence)`, "success");
      if (currentView === "overview") { loadPositions(); loadRiskStatus(); }
      if (currentView === "portfolio") loadPortfolio();
      break;
    case "analysis_complete":
      if (currentView === "overview") renderOpportunities(msg.data);
      break;
    case "bot_status":
      setBotStatusLine(msg.data.running);
      break;
  }
}

/* ---------------------------------------------------------------------- */
/* AI Market Analyst                                                        */
/* ---------------------------------------------------------------------- */

async function runAnalyst() {
  const symbolInput = document.getElementById("analyst-symbol");
  const symbol = symbolInput.value.trim().toUpperCase();
  const card = document.getElementById("analyst-result");
  const btn = document.getElementById("btn-analyst-run");
  if (!symbol) return;

  btn.disabled = true; btn.textContent = "Analyzing…";
  card.innerHTML = `<div class="empty-state">Analyzing ${symbol}…</div>`;
  try {
    const result = await api.marketAnalyst(symbol);
    card.innerHTML = `
      <div class="opp-row"><span class="muted">Trend</span><strong>${result.trend}</strong></div>
      <div class="opp-row"><span class="muted">RSI</span><strong>${result.rsi}</strong></div>
      <div class="opp-row"><span class="muted">Support / Resistance</span><strong>${result.support ?? "—"} / ${result.resistance ?? "—"}</strong></div>
      <div class="opp-row"><span class="muted">Confidence</span><strong>${result.confidence}%</strong></div>
      <p style="margin-top:16px;line-height:1.6">${result.summary}</p>
      <p class="muted" style="margin-top:14px;font-size:12px">${result.disclaimer}</p>
    `;
  } catch (err) {
    card.innerHTML = `<div class="empty-state">Failed to analyze ${symbol}: ${err.message}</div>`;
  } finally {
    btn.disabled = false; btn.textContent = "Analyze";
  }
}

/* ---------------------------------------------------------------------- */
/* Risk Calculator                                                          */
/* ---------------------------------------------------------------------- */

async function runRiskCalculator(e) {
  e.preventDefault();
  const card = document.getElementById("calc-result");
  card.innerHTML = `<div class="empty-state">Calculating…</div>`;
  try {
    const result = await api.riskCalculator({
      balance: parseFloat(document.getElementById("calc-balance").value),
      risk_percent: parseFloat(document.getElementById("calc-risk").value),
      entry_price: parseFloat(document.getElementById("calc-entry").value),
      stop_loss: parseFloat(document.getElementById("calc-sl").value),
      symbol: document.getElementById("calc-symbol").value.trim().toUpperCase(),
    });
    card.innerHTML = `
      <div class="opp-row"><span class="muted">Suggested Position Size</span><strong>${result.position_size_lots} lots</strong></div>
      <div class="opp-row"><span class="muted">Stop-Loss Distance</span><strong>${result.stop_loss_pips} pips</strong></div>
      <div class="opp-row"><span class="muted">Amount at Risk</span><strong>${fmtMoney(result.risk_amount)}</strong></div>
      <div class="opp-row"><span class="muted">Price Distance to SL</span><strong>${result.stop_distance_price}</strong></div>
    `;
  } catch (err) {
    card.innerHTML = `<div class="empty-state">${err.message}</div>`;
  }
}

/* ---------------------------------------------------------------------- */
/* Trading Journal                                                          */
/* ---------------------------------------------------------------------- */

async function loadJournal() {
  try {
    const [stats, trades] = await Promise.all([api.journalStats(), api.reportsTrades(30)]);

    document.getElementById("jr-total").textContent = stats.total_journaled;
    document.getElementById("jr-winrate").textContent = fmtPct(stats.win_rate);
    document.getElementById("jr-avgrr").textContent = stats.avg_rr !== null ? `1:${stats.avg_rr}` : "—";
    document.getElementById("jr-best-strategy").textContent = stats.best_strategy || "—";

    const byStrategyCard = document.getElementById("jr-by-strategy");
    byStrategyCard.innerHTML = !stats.by_strategy.length
      ? `<div class="empty-state">No journaled trades yet.</div>`
      : stats.by_strategy.map((s) => `
          <div class="opp-row">
            <span><strong>${s.strategy}</strong> <span class="muted">(${s.trades} trades, ${s.win_rate}% win rate)</span></span>
            <span class="${s.pnl >= 0 ? "up" : "down"}">${fmtMoney(s.pnl)}</span>
          </div>
        `).join("");

    const body = document.getElementById("jr-trades-body");
    body.innerHTML = !trades.length
      ? `<tr><td colspan="7" class="empty-state">No trades yet.</td></tr>`
      : trades.map((t) => `
          <tr>
            <td><strong>${t.symbol}</strong></td>
            <td><span class="opp-dir ${t.type}">${t.type}</span></td>
            <td class="${(t.profit || 0) >= 0 ? "up" : "down"}">${t.profit !== null ? fmtMoney(t.profit) : "—"}</td>
            <td><input type="text" class="jr-input" data-field="strategy" data-id="${t.id}" value="${t.strategy || ""}" placeholder="e.g. EMA crossover" style="width:120px;padding:6px;background:transparent;border:1px solid var(--card-border);border-radius:6px;color:var(--text-primary);font-size:12.5px"></td>
            <td><input type="text" class="jr-input" data-field="notes" data-id="${t.id}" value="${t.notes || ""}" placeholder="Why this trade?" style="width:140px;padding:6px;background:transparent;border:1px solid var(--card-border);border-radius:6px;color:var(--text-primary);font-size:12.5px"></td>
            <td><input type="text" class="jr-input" data-field="emotion" data-id="${t.id}" value="${t.emotion || ""}" placeholder="calm / fomo / etc" style="width:100px;padding:6px;background:transparent;border:1px solid var(--card-border);border-radius:6px;color:var(--text-primary);font-size:12.5px"></td>
            <td><button class="btn btn-ghost" data-explain="${t.id}">Explain</button></td>
          </tr>
        `).join("");

    body.querySelectorAll(".jr-input").forEach((input) => {
      input.addEventListener("change", async () => {
        try {
          await api.journalUpdate(input.dataset.id, { [input.dataset.field]: input.value });
          showToast("Journal updated", "success");
        } catch (err) { showToast(err.message, "error"); }
      });
    });

    body.querySelectorAll("[data-explain]").forEach((btn) => {
      btn.addEventListener("click", () => explainTrade(btn.dataset.explain));
    });
  } catch (err) { showToast(err.message, "error"); }
}

async function explainTrade(tradeId) {
  try {
    const result = await api.explainTrade(tradeId);
    alert(`${result.narrative}\n\n${result.study_note}\n\n${result.disclaimer}`);
  } catch (err) { showToast(err.message, "error"); }
}

/* ---------------------------------------------------------------------- */
/* Economic Calendar                                                        */
/* ---------------------------------------------------------------------- */

async function loadCalendar() {
  const body = document.getElementById("cal-body");
  try {
    const events = await api.calendarUpcoming(7);
    body.innerHTML = !events.length
      ? `<tr><td colspan="6" class="empty-state">No upcoming events.</td></tr>`
      : events.map((e) => `
          <tr>
            <td class="muted">${e.time}</td>
            <td><strong>${e.country}</strong></td>
            <td>${e.event}</td>
            <td><span class="tag ${e.impact === "high" ? "HIGH" : e.impact === "medium" ? "MEDIUM" : "LOW"}">${e.impact}</span></td>
            <td>${e.forecast ?? "—"}</td>
            <td class="muted">${e.previous ?? "—"}</td>
          </tr>
        `).join("");
  } catch (err) {
    body.innerHTML = `<tr><td colspan="6" class="empty-state">Failed to load calendar.</td></tr>`;
  }
}

/* ---------------------------------------------------------------------- */
/* Strategy Backtester                                                      */
/* ---------------------------------------------------------------------- */

async function runBacktest(e) {
  e.preventDefault();
  const tradesBody = document.getElementById("bt-trades-body");
  tradesBody.innerHTML = `<tr><td colspan="5" class="empty-state">Running backtest…</td></tr>`;

  try {
    const result = await api.backtest({
      symbol: document.getElementById("bt-symbol").value.trim().toUpperCase(),
      timeframe: document.getElementById("bt-timeframe").value,
      fast_period: parseInt(document.getElementById("bt-fast").value, 10),
      slow_period: parseInt(document.getElementById("bt-slow").value, 10),
      sl_pips: parseFloat(document.getElementById("bt-sl").value),
      tp_pips: parseFloat(document.getElementById("bt-tp").value),
      use_rsi_filter: document.getElementById("bt-rsi").value === "true",
    });

    document.getElementById("bt-trades").textContent = result.total_trades;
    document.getElementById("bt-winrate").textContent = fmtPct(result.win_rate);
    const pnlEl = document.getElementById("bt-pnl");
    pnlEl.textContent = fmtMoney(result.net_pnl);
    pnlEl.className = `stat-value ${result.net_pnl >= 0 ? "up" : "down"}`;
    document.getElementById("bt-drawdown").textContent = fmtPct(result.max_drawdown_percent);

    if (result.message) {
      tradesBody.innerHTML = `<tr><td colspan="5" class="empty-state">${result.message}</td></tr>`;
      return;
    }

    tradesBody.innerHTML = result.trades.map((t) => `
      <tr>
        <td><span class="opp-dir ${t.direction}">${t.direction}</span></td>
        <td>${t.entry}</td>
        <td>${t.exit}</td>
        <td class="${t.pnl >= 0 ? "up" : "down"}">${fmtMoney(t.pnl)}</td>
        <td class="muted">${t.reason}</td>
      </tr>
    `).join("");
  } catch (err) {
    tradesBody.innerHTML = `<tr><td colspan="5" class="empty-state">${err.message}</td></tr>`;
  }
}
