/* dashboard.js — powers dashboard.html: tabbed workspace (Overview, Market
   Scanner, AI Signals, Portfolio, Risk Manager, Reports), AI control center,
   live WebSocket updates including auto-trading bot activity. */

let currentSettings = { max_trades: 5 };
let currentView = "overview";

const VIEW_META = {
  overview:  { heading: "Welcome",         sub: "Live account snapshot & AI market intelligence" },
  scanner:   { heading: "Market Scanner",  sub: "Live confidence scan across the broader instrument universe" },
  signals:   { heading: "AI Signals",      sub: "Signal history generated by the analysis engine" },
  portfolio: { heading: "Portfolio",       sub: "Account balance, open positions, and trade history" },
  risk:      { heading: "Risk Manager",    sub: "Exposure, drawdown, and position sizing controls" },
  reports:   { heading: "Reports",         sub: "Performance breakdown across all closed trades" },
};

document.addEventListener("DOMContentLoaded", async () => {
  const user = await initShell("dashboard");
  if (!user) return;

  wireNav();
  wireButtons();
  connectWebSocket(handleWsMessage);

  await loadSettingsForCaps();

  const initialView = (location.hash || "#overview").replace("#", "");
  switchView(VIEW_META[initialView] ? initialView : "overview", user);
});

/* ---------------------------------------------------------------------- */
/* View switching                                                          */
/* ---------------------------------------------------------------------- */

function wireNav() {
  document.querySelectorAll(".nav-link[data-view]").forEach((el) => {
    el.addEventListener("click", (e) => {
      e.preventDefault();
      const view = el.dataset.view;
      history.replaceState(null, "", `#${view}`);
      switchView(view);
    });
  });
}

function switchView(view) {
  currentView = view;

  document.querySelectorAll(".view").forEach((el) => (el.hidden = true));
  document.getElementById(`view-${view}`).hidden = false;

  document.querySelectorAll(".nav-link").forEach((el) => {
    el.classList.toggle("active", el.dataset.view === view);
  });

  const meta = VIEW_META[view];
  document.getElementById("view-heading").textContent =
    view === "overview" && window.__username ? `Welcome, ${window.__username}` : meta.heading;
  document.getElementById("view-subheading").textContent = meta.sub;

  loadViewData(view);
}

async function loadViewData(view) {
  switch (view) {
    case "overview":
      await Promise.all([loadAccount(), loadPositions(), loadRiskStatus(), loadSignals(), loadBotStatus()]);
      break;
    case "scanner":
      await loadScanner();
      break;
    case "signals":
      await loadSignalHistory();
      break;
    case "portfolio":
      await loadPortfolio();
      break;
    case "risk":
      await loadRiskDetail();
      break;
    case "reports":
      await loadReports();
      break;
  }
}

/* ---------------------------------------------------------------------- */
/* Overview                                                                */
/* ---------------------------------------------------------------------- */

async function loadSettingsForCaps() {
  try {
    currentSettings = await api.getSettings();
    const el = document.getElementById("stat-max-trades");
    if (el) el.textContent = currentSettings.max_trades;
  } catch (_) { /* non-fatal */ }
}

async function loadAccount() {
  try {
    const acct = await api.account();
    document.getElementById("stat-balance").textContent = fmtMoney(acct.balance);
    document.getElementById("stat-equity").textContent = fmtMoney(acct.equity);
    document.getElementById("stat-currency").textContent = acct.currency;
    document.getElementById("stat-margin-level").textContent = fmtPct(acct.margin_level);

    const dot = document.getElementById("mt5-dot");
    const text = document.getElementById("mt5-text");
    dot.classList.add("on");
    dot.classList.remove("off");
    text.textContent = acct.mock ? "MT5 · Mock data" : `MT5 · ${acct.server}`;
  } catch (err) {
    showToast(err.message, "error");
  }
}

async function loadPositions() {
  const body = document.getElementById("positions-body");
  try {
    const positions = await api.positions();
    document.getElementById("stat-open-trades").textContent = positions.length;

    const dailyProfit = positions.reduce((sum, p) => sum + p.profit, 0);
    const sub = document.getElementById("stat-daily-profit");
    const subline = document.getElementById("stat-daily-profit-sub");
    sub.textContent = fmtMoney(dailyProfit);
    sub.className = `stat-value ${dailyProfit >= 0 ? "up" : "down"}`;
    subline.textContent = `${positions.length} open position(s)`;

    body.innerHTML = renderPositionsRows(positions, true);
    wireCloseButtons(body);
  } catch (err) {
    body.innerHTML = `<tr><td colspan="7" class="empty-state">Failed to load positions.</td></tr>`;
  }
}

function renderPositionsRows(positions, withClose) {
  if (!positions.length) {
    return `<tr><td colspan="7" class="empty-state">No open positions.</td></tr>`;
  }
  return positions.map((p) => `
    <tr>
      <td><strong>${p.symbol}</strong></td>
      <td><span class="opp-dir ${p.type}">${p.type}</span></td>
      <td>${p.volume}</td>
      <td>${p.open_price}</td>
      <td>${p.current_price}</td>
      <td class="${p.profit >= 0 ? "up" : "down"}">${fmtMoney(p.profit)}</td>
      <td>${withClose ? `<button class="btn btn-ghost" data-close-ticket="${p.ticket}">Close</button>` : ""}</td>
    </tr>
  `).join("");
}

function wireCloseButtons(container) {
  container.querySelectorAll("[data-close-ticket]").forEach((btn) => {
    btn.addEventListener("click", () => closeTrade(Number(btn.dataset.closeTicket)));
  });
}

async function loadRiskStatus() {
  const card = document.getElementById("risk-card");
  try {
    const r = await api.riskStatus();
    card.innerHTML = riskStatusHtml(r);
  } catch (err) {
    card.innerHTML = `<div class="empty-state">Failed to load risk status.</div>`;
  }
}

function riskStatusHtml(r) {
  return `
    <div class="opp-row"><span class="muted">Daily Risk</span><strong>${fmtPct(r.daily_risk_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Risk Used Today</span><strong>${fmtPct(r.daily_risk_used_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Exposure</span><span class="tag ${r.exposure}">${r.exposure}</span></div>
    <div class="opp-row"><span class="muted">Drawdown</span><strong>${fmtPct(r.drawdown_percent)}</strong></div>
    <div class="opp-row"><span class="muted">Open / Max Trades</span><strong>${r.open_trades} / ${r.max_trades}</strong></div>
    <div class="opp-row"><span class="muted">Max Daily Loss</span><strong>${fmtPct(r.max_daily_loss_percent)}</strong></div>
  `;
}

async function loadSignals() {
  try {
    const signals = await api.signals(6);
    renderOpportunities(signals);
  } catch (_) { /* leave initial empty-state */ }
}

function renderOpportunities(signals) {
  const card = document.getElementById("opportunities-card");
  if (!signals.length) {
    card.innerHTML = `<div class="empty-state">Run <strong>Analyze Markets</strong> to generate AI signals.</div>`;
    return;
  }
  card.innerHTML = signals.map((s) => `
    <div class="opp-row">
      <div class="opp-symbol">${s.symbol} <span class="opp-dir ${s.direction}">${s.direction}</span></div>
      <div style="display:flex;align-items:center;gap:10px;">
        <div class="confidence-bar-track"><div class="confidence-bar-fill" style="width:${s.confidence}%"></div></div>
        <span class="confidence-pct">${s.confidence}%</span>
      </div>
    </div>
  `).join("");
}

async function loadBotStatus() {
  try {
    const status = await api.botStatus();
    setBotStatusLine(status.running);
  } catch (_) { /* ignore */ }
}

function setBotStatusLine(running) {
  const el = document.getElementById("bot-status-line");
  if (el) el.textContent = `Bot status: ${running ? "🟢 Running (Auto Mode) — checks every ~45s" : "⚪ Stopped"}`;
}

function wireButtons() {
  document.getElementById("btn-analyze").addEventListener("click", runAnalysis);
  document.getElementById("btn-generate").addEventListener("click", runAnalysis);

  const signalsGenBtn = document.getElementById("btn-signals-generate");
  if (signalsGenBtn) signalsGenBtn.addEventListener("click", async () => {
    await runAnalysis();
    await loadSignalHistory();
  });

  const rescanBtn = document.getElementById("btn-rescan");
  if (rescanBtn) rescanBtn.addEventListener("click", loadScanner);

  document.getElementById("btn-start-bot").addEventListener("click", async (e) => {
    e.target.disabled = true;
    try {
      const status = await api.botStart();
      setBotStatusLine(status.running);
      showToast("Auto mode started — bot will trade on high-confidence signals", "success");
    } catch (err) {
      showToast(err.message, "error");
    } finally {
      e.target.disabled = false;
    }
  });

  document.getElementById("btn-stop-bot").addEventListener("click", async (e) => {
    e.target.disabled = true;
    try {
      const status = await api.botStop();
      setBotStatusLine(status.running);
      showToast("Bot stopped", "success");
    } catch (err) {
      showToast(err.message, "error");
    } finally {
      e.target.disabled = false;
    }
  });
}

async function runAnalysis() {
  const btn = document.getElementById("btn-analyze");
  const btn2 = document.getElementById("btn-generate");
  if (btn) btn.disabled = true;
  if (btn2) btn2.disabled = true;
  if (btn) btn.textContent = "🔍 Analyzing…";
  try {
    const results = await api.analyze();
    renderOpportunities(results);
    if (currentView === "overview") await loadPositions();
    showToast(`Analysis complete — ${results.length} symbols scanned`, "success");
  } catch (err) {
    showToast(err.message, "error");
  } finally {
    if (btn) { btn.disabled = false; btn.textContent = "🔍 Analyze Markets"; }
    if (btn2) btn2.disabled = false;
  }
}

async function closeTrade(ticket) {
  try {
    await api.tradeClose(ticket);
    showToast(`Position ${ticket} closed`, "success");
    await loadViewData(currentView);
  } catch (err) {
    showToast(err.message, "error");
  }
}

/* ---------------------------------------------------------------------- */
/* Market Scanner                                                          */
/* ---------------------------------------------------------------------- */

async function loadScanner() {
  const body = document.getElementById("scanner-body");
  body.innerHTML = `<tr><td colspan="6" class="empty-state">Scanning…</td></tr>`;
  try {
    const rows = await api.scanner();
    if (!rows.length) {
      body.innerHTML = `<tr><td colspan="6" class="empty-state">No data.</td></tr>`;
      return;
    }
    body.innerHTML = rows.map((r) => `
      <tr>
        <td><strong>${r.symbol}</strong></td>
        <td>${r.price ?? "—"}</td>
        <td class="${r.change_pct >= 0 ? "up" : "down"}">${r.change_pct >= 0 ? "+" : ""}${r.change_pct}%</td>
        <td><span class="opp-dir ${r.direction}">${r.direction}</span></td>
        <td>
          <div style="display:flex;align-items:center;gap:10px;">
            <div class="confidence-bar-track" style="width:80px"><div class="confidence-bar-fill" style="width:${r.confidence}%"></div></div>
            <span class="confidence-pct">${r.confidence}%</span>
          </div>
        </td>
        <td><span class="tag ${r.risk}">${r.risk}</span></td>
      </tr>
    `).join("");
  } catch (err) {
    body.innerHTML = `<tr><td colspan="6" class="empty-state">Failed to scan markets.</td></tr>`;
  }
}

/* ---------------------------------------------------------------------- */
/* AI Signals (history)                                                    */
/* ---------------------------------------------------------------------- */

async function loadSignalHistory() {
  const body = document.getElementById("signals-body");
  try {
    const signals = await api.signals(30);
    if (!signals.length) {
      body.innerHTML = `<tr><td colspan="6" class="empty-state">No signals yet — click Generate New Signals.</td></tr>`;
      return;
    }
    body.innerHTML = signals.map((s) => `
      <tr>
        <td class="muted">${s.created_at}</td>
        <td><strong>${s.symbol}</strong></td>
        <td><span class="opp-dir ${s.direction}">${s.direction}</span></td>
        <td>${s.confidence}%</td>
        <td><span class="tag ${s.risk}">${s.risk}</span></td>
        <td class="muted">${(s.reason || []).join(", ")}</td>
      </tr>
    `).join("");
  } catch (err) {
    body.innerHTML = `<tr><td colspan="6" class="empty-state">Failed to load signal history.</td></tr>`;
  }
}

/* ---------------------------------------------------------------------- */
/* Portfolio                                                                */
/* ---------------------------------------------------------------------- */

async function loadPortfolio() {
  try {
    const [acct, positions, history] = await Promise.all([
      api.account(), api.positions(), api.history(30),
    ]);

    document.getElementById("pf-balance").textContent = fmtMoney(acct.balance);
    document.getElementById("pf-equity").textContent = fmtMoney(acct.equity);
    document.getElementById("pf-margin").textContent = fmtMoney(acct.free_margin);
    document.getElementById("pf-leverage").textContent = `1:${acct.leverage}`;

    const posBody = document.getElementById("pf-positions-body");
    posBody.innerHTML = renderPositionsRows(positions, true);
    wireCloseButtons(posBody);

    const histBody = document.getElementById("pf-history-body");
    if (!history.length) {
      histBody.innerHTML = `<tr><td colspan="5" class="empty-state">No trade history yet.</td></tr>`;
    } else {
      histBody.innerHTML = history.map((h) => `
        <tr>
          <td><strong>${h.symbol}</strong></td>
          <td><span class="opp-dir ${h.type}">${h.type}</span></td>
          <td>${h.volume}</td>
          <td class="${h.profit >= 0 ? "up" : "down"}">${fmtMoney(h.profit)}</td>
          <td class="muted">${h.closed_at}</td>
        </tr>
      `).join("");
    }
  } catch (err) {
    showToast(err.message, "error");
  }
}

/* ---------------------------------------------------------------------- */
/* Risk Manager (detail)                                                   */
/* ---------------------------------------------------------------------- */

async function loadRiskDetail() {
  const card = document.getElementById("risk-detail-card");
  try {
    const r = await api.riskStatus();
    card.innerHTML = riskStatusHtml(r);
  } catch (err) {
    card.innerHTML = `<div class="empty-state">Failed to load risk status.</div>`;
  }
}

/* ---------------------------------------------------------------------- */
/* Reports                                                                  */
/* ---------------------------------------------------------------------- */

async function loadReports() {
  try {
    const [summary, trades] = await Promise.all([
      api.reportsSummary(), api.reportsTrades(50),
    ]);

    document.getElementById("rp-pnl").textContent = fmtMoney(summary.total_pnl);
    document.getElementById("rp-pnl").className = `stat-value ${summary.total_pnl >= 0 ? "up" : "down"}`;
    document.getElementById("rp-winrate").textContent = fmtPct(summary.win_rate);
    document.getElementById("rp-best").textContent = fmtMoney(summary.best_trade);
    document.getElementById("rp-worst").textContent = fmtMoney(summary.worst_trade);

    const bySymbolCard = document.getElementById("rp-by-symbol");
    if (!summary.by_symbol.length) {
      bySymbolCard.innerHTML = `<div class="empty-state">No closed trades yet.</div>`;
    } else {
      bySymbolCard.innerHTML = summary.by_symbol.map((s) => `
        <div class="opp-row">
          <span><strong>${s.symbol}</strong> <span class="muted">(${s.trades} trades)</span></span>
          <span class="${s.pnl >= 0 ? "up" : "down"}">${fmtMoney(s.pnl)}</span>
        </div>
      `).join("");
    }

    const tradesBody = document.getElementById("rp-trades-body");
    if (!trades.length) {
      tradesBody.innerHTML = `<tr><td colspan="4" class="empty-state">No trades yet.</td></tr>`;
    } else {
      tradesBody.innerHTML = trades.map((t) => `
        <tr>
          <td><strong>${t.symbol}</strong></td>
          <td><span class="opp-dir ${t.type}">${t.type}</span></td>
          <td class="${(t.profit || 0) >= 0 ? "up" : "down"}">${t.profit !== null ? fmtMoney(t.profit) : "—"}</td>
          <td><span class="tag ${t.status === "OPEN" ? "MEDIUM" : "LOW"}">${t.status}</span></td>
        </tr>
      `).join("");
    }
  } catch (err) {
    showToast(err.message, "error");
  }
}

/* ---------------------------------------------------------------------- */
/* WebSocket events                                                         */
/* ---------------------------------------------------------------------- */

function handleWsMessage(msg) {
  switch (msg.event) {
    case "trade_opened":
    case "trade_closed":
      if (currentView === "overview") { loadPositions(); loadRiskStatus(); }
      if (currentView === "portfolio") loadPortfolio();
      break;
    case "bot_trade":
      showToast(
        `🤖 Bot opened ${msg.data.type} ${msg.data.symbol} (${msg.data.confidence}% confidence)`,
        "success"
      );
      if (currentView === "overview") { loadPositions(); loadRiskStatus(); }
      if (currentView === "portfolio") loadPortfolio();
      break;
    case "analysis_complete":
      if (currentView === "overview") renderOpportunities(msg.data);
      break;
    case "bot_status":
      setBotStatusLine(msg.data.running);
      break;
    case "price_update":
      // Reserved for a future live ticker on the scanner view.
      break;
  }
}
